name: Build inference-benchmarker

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Rust checks:
    permissions:
      pull-requests: write
      contents: read
    uses: ./.github/workflows/rust.yaml
  Build Docker image:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build.yaml
    needs: rust