name: Secret Leaks

on:
  push:

jobs:
  trufflehog:
    runs-on:
      group: aws-general-8-plus
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --exclude-globs='test_data/.*'
